In [259]:
import pandas as pd
import numpy as np

In [260]:
data = pd.read_csv('C:\\Users\\RAHUL\\Desktop\\TrainDecision.csv')

In [261]:
data

    Day   Outlook  Temp Humidity    Wind Play
0     1     Sunny   Hot     High    Weak   No
1     2     Sunny   Hot     High  Strong   No
2     3  Overcast   Hot     High    Weak  Yes
3     4      Rain  Mild     High    Weak  Yes
4     5      Rain  Cool   Normal    Weak  Yes
5     6      Rain  Cool   Normal  Strong   No
6     7  Overcast  Cool   Normal  Strong  Yes
7     8     Sunny  Mild     High    Weak   No
8     9     Sunny  Cool   Normal    Weak  Yes
9    10      Rain  Mild   Normal    Weak  Yes
10   11     Sunny  Mild   Normal  Strong  Yes
11   12  Overcast  Mild     High  Strong  Yes
12   13  Overcast   Hot   Normal    Weak  Yes
13   14      Rain  Mild     High  Strong   No

In [262]:
def entropy(value):
    entro=0
    for i in range(len(value)):
        if value[i]==0:
            return 0;
        else:
            entro+=-(value[i]/sum(value))*np.log2((value[i]/sum(value)))
    return entro

In [263]:
data.columns

Index(['Day', 'Outlook', 'Temp', 'Humidity', 'Wind', 'Play'], dtype='object')

In [264]:
elements,number=np.unique(data["Outlook"],return_counts=True)
elements
d=data.iloc[:,1:5]
d

     Outlook  Temp Humidity    Wind
0      Sunny   Hot     High    Weak
1      Sunny   Hot     High  Strong
2   Overcast   Hot     High    Weak
3       Rain  Mild     High    Weak
4       Rain  Cool   Normal    Weak
5       Rain  Cool   Normal  Strong
6   Overcast  Cool   Normal  Strong
7      Sunny  Mild     High    Weak
8      Sunny  Cool   Normal    Weak
9       Rain  Mild   Normal    Weak
10     Sunny  Mild   Normal  Strong
11  Overcast  Mild     High  Strong
12  Overcast   Hot   Normal    Weak
13      Rain  Mild     High  Strong

In [281]:
#print(out)
g=0
col=d.columns
for k in range(len(col)):
    print(col[k])
    out=data[col[k]]
    p=[]
    q=[]
    elements,number=np.unique(data[col[k]],return_counts=True)
    print(elements)
    for j in range(len(elements)):
        yes=0
        no=0
        for i in range(len(out)):

            if out[i]==elements[j]:
                if test[i]=='Yes':
                    yes=yes+1
                else:
                    no+=1
        
        print(elements[j],yes,no)
        gain=((sum([yes,no])/14)*entropy([yes,no]))
        print(sum([yes,no]))
        p.append(entropy([yes,no]))
        g=g+gain
        print(g)
    infogain=entr-g
    print(infogain)
    print(p)
p
g

Outlook
['Overcast' 'Rain' 'Sunny']
Overcast 4 0
4
0.0
Rain 3 2
5
0.3467680694480959
Sunny 2 3
5
0.6935361388961918
0.24674981977443933
[0, 0.9709505944546686, 0.9709505944546686]
Temp
['Cool' 'Hot' 'Mild']
Cool 3 1
4
0.9253298887416583
Hot 2 2
4
1.2110441744559441
Mild 4 2
6
1.6045995319078683
-0.6643135732372372
[0.8112781244591328, 1.0, 0.9182958340544896]
Humidity
['High' 'Normal']
High 3 4
7
2.097213599924994
Normal 6 1
7
2.393049989216158
-1.4527640305455267
[0.9852281360342515, 0.5916727785823275]
Wind
['Strong' 'Weak']
Strong 3 3
6
2.8216214177875862
Weak 6 2
8
3.2852089174785193
-2.344922958807888
[1.0, 0.8112781244591328]

3.2852089174785193

In [271]:
elements,number=np.unique(data["Play"],return_counts=True)

In [267]:
elements

array(['No', 'Yes'], dtype=object)

In [268]:
print(number[0],number[1])

5 9

In [269]:
entr=entropy([number[0],number[1]])
print(entr)

0.9402859586706311